# Generated by Django 5.1.1 on 2024-10-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imdb_id', models.TextField(blank=True, null=True, unique=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('original_language', models.TextField(blank=True, null=True)),
                ('release_date', models.IntegerField(blank=True, null=True)),
                ('original_title', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('poster_path', models.TextField(blank=True, null=True)),
                ('watched', models.BooleanField(default=False)),
                ('recommended', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'movie',
                'managed': True,
            },
        ),
    ]
